README.md
legate.py

Added new environment variables for several launcher options that are likely to be relatively constant on a given system.

Added ENVVARs for some launcher options.

---

legate/core/legion.py

Requires the changes at https://gitlab.com/StanfordLegion/legion/-/merge_requests/387 to first be merged into legate_stable.

Support initializing FieldSpace from existing handle

---

legate/core/launcher.py
legate/core/operation.py
legate/core/partition.py
legate/core/runtime.py
legate/core/shape.py
legate/core/solver.py
legate/core/store.py
legate/core/transform.py
src/legate_c.h
src/runtime/projection.cc

This PR contains a series of changes to improve the auto-partitioner in Legate Core.

Improve the auto-partitioner, part 1

---

legate/core/legion.py

This PR relaxes overzealous checks on point dimensions.

Fix overzealous checks on dimensions

---

legate/core/__init__.py
legate/core/operation.py
legate/core/types.py

This PR includes changes to add API calls to register and retrieve reduction operators.

Interface for registering and retrieving reduction operators

---

legate/core/constraints.py
legate/core/operation.py
legate/core/runtime.py
legate/core/solver.py

This PR removes objects cycles involving Legate that were preventing them from being collected by Python's reference counting scheme.

Object cycle fix

---

install.py

Before making a release we pin a tested Legion commit on that release
branch, so there is no need to have a special branch for Legate
development anymore.

Always pull Legion control_replication in source checkout builds

---

src/core/mapping/base_mapper.cc

This PR is to correctly handle cases where one instance is used by multiple mappings.

Bug fix for base mapper

---

legate/core/runtime.py

This PR is the same as #99, but for `branch-22.01`.

Fix for deferred detachments (back-ported)

---

install.py
src/legate.mk

Together with https://gitlab.com/StanfordLegion/legion/-/merge_requests/416 we will have full end-to-end minimal recompilation and dependency tracking, including header file changes.
Also, changes to Legion/Realm options (e.g. `DEBUG` vs `RELEASE`) will properly trigger a full recompilation even in `--noclean` mode.

Build system improvements

---

src/core/mapping/base_mapper.cc

Remove an overzealous assertion

---

legate/core/context.py
legate/core/operation.py
src/core/legate_c.h
src/core/mapping/base_mapper.cc
src/core/mapping/base_mapper.h

This PR implements cyclic task distribution for manually parallelized tasks. We will later add a mapper call to override this behavior if necessary.

Cyclic distribution

---

.gitignore
conda/core_dev.yml
install.py

This allows us to use latest setuptools

Do python install on custom dir w/o eggs

---

src/core/runtime/context.cc
src/core/runtime/context.h

APIs to query launch shape

---

conda/core_dev.yml
install.py
legate/core/communicator.py
legate/core/context.py
legate/core/launcher.py
legate/core/operation.py
legate/core/runtime.py
legate/core/solver.py
src/Makefile
src/core.mk
src/core/comm/comm.cc
src/core/comm/comm.h
src/core/comm/comm_nccl.cu
src/core/comm/comm_nccl.h
src/core/comm/communicator.h
src/core/legate_c.h
src/core/runtime/context.cc
src/core/runtime/context.h
src/core/runtime/runtime.cc
src/core/utilities/deserializer.cc
src/core/utilities/deserializer.h

This PR adds APIs for communicators and support for NCCL.

Communicator support

---

legate/core/constraints.py
legate/core/partition.py
legate/core/solver.py

This PR fixes/works around bugs in the auto-partitioner.

Some fixes for auto-partitioner

---

legate/core/launcher.py
legate/core/operation.py

This PR makes the bit-rotted Legate copy code up to date with the new partition symbol system.

Update Legate copy

---

legate/core/constraints.py
legate/core/context.py
legate/core/operation.py
legate/core/partition.py
legate/core/runtime.py
legate/core/shape.py
legate/core/solver.py
legate/core/store.py
src/core/data/store.cc
src/core/data/store.h
src/core/data/store.inl
src/core/runtime/context.cc

This PR teaches Legate Core how to manage uneven partitions from variable size outputs.

Support for uneven partitions

---

legate/core/context.py
legate/core/operation.py
legate/core/projection.py
legate/core/runtime.py
legate/core/transform.py
src/core/data/store.cc
src/core/data/store.h
src/core/legate_c.h
src/core/runtime/context.cc
src/core/runtime/projection.cc

This PR is to add support for reduction task trees.

Support for reduction tree construction

---

legate/core/operation.py
legate/core/solver.py

This PR is to extend the auto-partitioner to handle partitions with different color spaces, which can arise with indirect copies. (See cuNumeric [#203](https://github.com/nv-legate/cunumeric/issues/203) for the detail.)

Support for unaligned color spaces

---

legate/core/communicator.py
legate/core/launcher.py

This PR adds an optional argument to the task launcher to turn off the local function optimization when necessary. The unique ID generation for NCCL is one such case.

Turn off local function optimization for NCCL initialization

---

src/core/data/store.inl

This PR contains a fix to correctly use the revised output region API.

Fix for output region

---

legate/core/_legion/region.py
src/core/mapping/base_mapper.cc

Another quick fix to catch up the changes with unbound stores.

Unbound store fix

---

legate/core/communicator.py
legate/core/operation.py
legate/core/runtime.py
src/core/legate_c.h
src/core/runtime/projection.cc
src/core/runtime/shard.cc

This PR fixes communicators so that they can be passed to N-D task launches.

Communicators for N-D task launches

---

legate/core/_legion/region.py
legate/core/context.py
legate/core/launcher.py
legate/core/operation.py
legate/core/runtime.py
legate/core/solver.py
legate/core/store.py
src/core/data/buffer.h
src/core/data/store.h
src/core/data/store.inl
src/core/mapping/base_mapper.cc
src/core/utilities/deserializer.cc

This PR updates several components to support N-D unbound stores.

Updates for N-D unbound stores

---

legate/core/solver.py

The solver wasn't calculating the equivalence class ids correctly. This PR fixes the issue.

Fix for the constraint solver

---

legate/core/launcher.py

Requirement analyzers were using Python sets that aren't deterministic. This PR replaces them with `OrderedSet`s so the analyzers are complaint with control replication. This should fix [#299](https://github.com/nv-legate/cunumeric/issues/299).

Use ordered sets in requirement analyzers for determinism

---

install.py

legate.mk already uses std=c++17

Compile everything using C++17

---

conda/conda-build/build.sh
conda/conda-build/meta.yaml

- Switch to using openblas from conda instead of downloading and compiling during legate compilation
- Fix some formatting in the conda recipe

Switch conda recipe to rely on conda openblas

---

conda/conda-build/build.sh
conda/conda-build/meta.yaml

Reverts nv-legate/legate.core#230

Revert "Switch conda recipe to rely on conda openblas"

---

conda/conda-build/build.sh
conda/conda-build/conda_build_config.yaml
conda/conda-build/meta.yaml

Ongoing work on conda recipes (update PR description before merging).

[WIP] Conda recipes improvements

---

conda/environment-test-3.10.yml
conda/environment-test-3.8.yml
conda/environment-test-3.9.yml
legate/core/communicator.py

This PR adds `colorama` as a tests dependency, and also bymps the min `mypy` version to `0.961`. 
Additionally, a few small type issues were fixed (cc @magnatelee @marcinz these will just continue to randomly crop up until type checking is enforced in CI or a pre-commit hook, or both)

Minor env and mypy updates

---

legate/core/communicator.py
src/core/comm/alltoall_thread_mpi.cc
src/core/comm/alltoallv_thread_mpi.cc
src/core/comm/coll.cc
src/core/comm/coll.h
src/core/comm/comm_cpu.cc
src/core/legate_c.h

The communicators are created on demand now.

Get rid of the LEGATE_MAX_CPU_COMMS

---

conda/environment-test-3.10.yml
conda/environment-test-3.8.yml
conda/environment-test-3.9.yml

Small PR to keep legate conda envs in sync with cunumeric envs

add types-docutils to envs

---

install.py

Some users experienced issues that may be fixed in the new legion version.

Update legion commit to the latest

---

install.py

Co-authored-by: Marcin Zalewski <mzalewski@nvidia.com>

Release v22.05.03

---

legate/core/store.py

This PR is to stop introducing `Shift` transforms of offset 0

Eliminate null shift transforms

---

src/core/data/store.cc
src/core/data/store.h
src/core/data/transform.cc
src/core/data/transform.h
src/core/mapping/task.cc
src/core/mapping/task.h
src/core/utilities/deserializer.cc
src/core/utilities/deserializer.h
src/core/utilities/deserializer.inl

* Extract out the linked structure from store transforms
* Correctly calculate the dimension in remove_transform using a store transform popped out from the stack

Store refactoring

---

legate/core/runtime.py
legate/core/shape.py
src/core/data/store.cc

Correctly handle 0-D stores backed by region fields

---

src/core/data/store.cc
src/core/data/store.h
src/core/data/store.inl

* Catch dimension mismatches and invalid return requests
* Wrap all debug asserts with the DEBUG_LEGATE macro

Two improvements to error handling

---

bind.sh
legate.py

Skip conduit check when binding

---

docs/legate/core/source/conf.py
legate.py
legate/core/corelib.py
legate/core/projection.py
legate/core/solver.py
legate/core/types.py

This PR addresses some issues reported by a local run of CodeQL using the full LGTM query set.

Misc minor cleanup

---

legate/core/__init__.py
legate/core/allocation.py
legate/core/communicator.py
legate/core/context.py
legate/core/io.py
legate/core/launcher.py
legate/core/operation.py
legate/core/partition.py
legate/core/restriction.py
legate/core/runtime.py
legate/core/solver.py
legate/core/store.py
legate/core/transform.py

This PR eliminates references to the runtime object in all non-runtime components to simplify the object graph.

Refactoring to make the runtime object singleton

---

.github/release.yml

Add configuration for how to classify PRs based on labels.

Add GitHub changelog configuration

---

legate/driver/util.py

Fixes #393.
This commit fixes a bug where the legate driver could not find some internal modules.

legate/driver: fix driver legion_module path

---

.github/workflows/ci.yml

In addition to commit-triggered CI runs, also run it on schedule.

Run CI on schedule

---

legate/core/runtime.py

* Perform consensus match more frequently for bigger free fields
* Minor cleanup

Adjust consensus match frequency based on field sizes (#402)

---

src/core/data/store.cc
src/core/mapping/base_mapper.cc
src/legate_defines.h

Port of https://github.com/nv-legate/legate.core/pull/409 onto branch-22.12

Legion bug WAR: don't instantiate futures on framebuffer

---

.github/workflows/ci.yml

Fix the minutes (run only once), and change to every 6 hours.

Adjust the schedule of the CI runs

---

legate/core/runtime.py
src/core/mapping/core_mapper.cc

* Make sure we test LRU mechanism in debug mode
* Make sure we don't create fields on a dead region manager

Revive dead region managers on field allocations (#418)

---

legate/tester/stages/_linux/gpu.py
tests/unit/legate/tester/stages/_linux/test_gpu.py

This PR fixes a one character mistake I made in the GPU shard computation....
> **Manolis Papadakis**
[13:25] look at the positive side
[13:25] we just increased GPU testing efficiency by 100%

Fix GPU shard computation

---

.pre-commit-config.yaml
legate/tester/stages/test_stage.py
tests/unit/legate/driver/test_config.py
tests/unit/legate/jupyter/test_kernel.py
tests/unit/legate/tester/stages/test_test_stage.py
tests/unit/legate/tester/stages/test_util.py
tests/unit/legate/util/test_system.py

This PR fixes up some mypy issue in the tests, and adds the `tests` directory to the `mypy` pre-commit check.

Fix up mypy errors in tests

---

legate/core/partition.py
legate/core/runtime.py
legate/core/store.py

See individual commit comments for details.

fix several reference cycle / leak related bugs

---

legate/core/corelib.py
legate/core/legate.py
legate/core/runtime.py
legate/core/types.py
legate/jupyter/_legion_kernel.py
legate/jupyter/magic.py
legate/tester/args.py
legate/timing/timing.py
tests/unit/legate/util/test_ui.py

This PR adds types for `__legate_data_interface__` that can also be added to downstream projects.
Not sure about the names, happy to change based on any suggestions.

Add type for LegateDataInterface

---

src/core/mapping/base_mapper.cc

src/core/mapping: adjust indirect copy mapping for GPUs

---

src/core/mapping/base_mapper.cc

This commit adjusts an assertion in the base mapper for use with the collective branch of legion.

src/core/mapping: temporary fix to base_mapper for collective branch

---

src/core/task/return.cc

Don't access stream pools unless we're on GPUs

---

.github/workflows/ci.yml
tests/unit/legate/driver/test_main.py
tests/unit/legate/jupyter/test_main.py
tests/unit/legate/tester/test_config.py
tests/unit/legate/util/test_system.py

This PR added the plain python `pytest` unit tests as well as a Mypy check to legate CI

Add machinery for legate.core base tests

---

legate/core/store.py

legate/core: reset storage key partition in Store::reset_key_partition

---

BUILD.md
README.md
scripts/generate-conda-envs.py

Improve build documentation

---

src/core/mapping/base_mapper.cc
src/core/runtime/projection.cc
src/core/runtime/projection.h

src/core: guard against missing projection functors in collective check

---

conda/conda-build/build.sh

Co-authored-by: Marcin Zalewski <mzalewski@nvidia.com>

Update the architectures built in conda package (backport #545)

---

install.py

Fix the default Legion commit to the version tested at the time of the release.

Fix the default Legion version

---

legate/driver/driver.py

This should get cunumeric tests working again cc @manopapad

Don't report cn version for now

---

legate/tester/__init__.py
tests/unit/legate/tester/test___init__.py

See discussion: https://github.com/nv-legate/cunumeric/issues/801

Change default --cpus value to 2

---

scripts/generate-conda-envs.py

ref: https://github.com/nv-legate/cunumeric/pull/822

Set sphinx theme minver to 0.13

---

cmake/legate_helper_functions.cmake
examples/hello/setup.py

Fixes for the hello world tutorial

Tutorial editable install fix

---

conda/conda-build/conda_build_config.yaml
scripts/generate-conda-envs.py
setup.py

* Updating for py311
* Document support for python 3.11
---------

Add support for Python 3.11 (#608)

---

BUILD.md
CONTRIBUTING.md
README.md
docs/legate/core/Makefile

Companion to https://github.com/nv-legate/cunumeric/pull/853

Add docs linkcheck job

---

.github/workflows/ci-gh.yml

Adding ci-gh.yml to build legate.core documentation on a github runner.

---

.github/workflows/ci-gh.yml

Plus a few other cosmetic changes.

Adding a GH CI step for running the documentation link checker.

---

src/core/mapping/base_mapper.cc

The old code would end up filling in more futures_locations than task.futures, in cases where an Output Store was Future-backed.
It was also implicitly assuming that mappings for Future-backed Stores appeared in the same order as Task Futures.

Fix the mapping of Futures in the BaseMapper

---

src/core/comm/mpi_comm.cc

Suggestion from @eddy16112 re: different MPI setup on some specific systems.

call MPI_Init_thread when necessary

---

cmake/legate_helper_functions.cmake

Committing the fix by @jjwilke

Fix a "file-not-found" bug during repeated editable installs

---

legate/core/runtime.py

Non-monorepo strikes again :disappointed: Usually I check full cunumeric tests manually locally but evidently forgot this time.

Fix error w/ disable mpi setting

---

.github/workflows/gh-test.yml

…nvironment from the YAML file. I expect mamba will now be able to install the dependencies legate.core needs.

Fix failing GH CI workflows due to environment resolution issues

---

legate/tester/stages/test_stage.py

This PR reverts the changes in #761 for now, since those changes seem to exacerbate the OOM issues.

revert sharding change

---

CMakeLists.txt
cmake/versions.json

- Update version of legate.core in `CMakeLists.txt`
- Bump up the version of Legion
- ~~Bump up the version of Thrust~~

Bump up the version of legate.core

---

.github/workflows/ci-gh-cpu-build-and-test.yml
.github/workflows/ci-gh-gpu-build-and-test.yml
.github/workflows/gh-build.yml
.github/workflows/gh-test.yml

Use repository variables as possible. 

---

legate/core/runtime.py

Just wait on the futures instead of spin-looping

Avoid gc infinite loop at runtime destruction time

---

docs/legate/core/source/api/classes.rst
docs/legate/core/source/api/machine.rst
docs/legate/core/source/api/routines.rst
legate/core/__init__.py
legate/core/machine.py

@bryevdv I haven't found a good way to document properties of dataclasses. Any suggestions?

API reference for resource scoping

---

.github/workflows/ci-gh-build-release.yml
.github/workflows/gh-build-and-test.yml
.github/workflows/gh-build.yml
.github/workflows/gh-test.yml
conda/conda-build/conda_build_config.yaml
conda/conda-build/meta.yaml
continuous_integration/scripts/build-legate-conda
continuous_integration/scripts/build-legate-cpp
continuous_integration/scripts/conda-utils
continuous_integration/scripts/run-test-or-analysis

- Does not enable ucx for MAC.

Enable ucx in legate.core builds.

---

.github/workflows/ci-gh-docs.yml
continuous_integration/scripts/build-legate
continuous_integration/scripts/make-conda-env

Update legate-build.
Please refer to the earlier PR-900 for comments:
(https://github.com/nv-legate/legate.core/pull/900)

Retarget docs build on self hosted runner

---

examples/io/src/read_file.cc

See https://github.com/nv-legate/legate.core/issues/904#issuecomment-1839813308

Fix compilation error with std::min on MacOS

---

.github/workflows/gh-build-and-test.yml
continuous_integration/scripts/run-test-or-analysis

We don't need mypy outside of precommit.

Do not run mypy tests outside of pre-commit

---

legate/core/_legion/future.py
legate/core/store.py

https://github.com/nv-legate/legate.core/pull/364 had removed the check of Region ID in `same_handle`, but that is necessary for correct behavior IIUC.

Fix bugs with overlap handling

---

scripts/generate-conda-envs.py

https://github.com/TvoroG/pytest-lazy-fixture/issues/65

Work around a pytest-lazy-fixture issue
