nv-legate/legate.core

src/.clang-format
src/data/scalar.cc
src/data/scalar.h
src/data/store.cc
src/data/store.h
src/data/store.inl
src/data/transform.cc
src/data/transform.h
src/gpu/cudalibs.h
src/runtime/context.cc
src/runtime/context.h
src/task/task.h
src/utilities/deserializer.cc
src/utilities/deserializer.h
src/utilities/dispatch.h
src/utilities/span.h

This PR is to force left alignment for pointers and references in C++ source files. Previously, we let the formatter to choose the most common alignment in each file (i.e., `DerivePointerAlignment` set to `true`), and this made the files end up using different alignments.

Force left alignment for pointers and references

---

legate/core/transform.py

This PR fixes a bug in delinearization's inversion function, which was incorrectly projecting the color space of the inverted partition.

Fix for delinearization's inversion function

---

.github/workflows/ci.yml

We want images for branches as we need to match the core image to the library version we are using in CI.

When generating CI images, name them after the branch

---

legate/core/partition.py
legate/core/runtime.py

This PR is to cache index partitions created for index spaces. Due to many one-off Legate stores created for alignments, the cache in Legate store alone doesn't save much on this.

Cache index partitions created for index spaces

---

legate/core/launcher.py
legate/core/legion.py
legate/core/operation.py
legate/core/runtime.py
legate/core/solver.py
legate/core/store.py

"Scalar", as used by legate.numpy, assumes both that (a) the Store represents exactly one value, and (b) it is backed by a Future. (a) can happen without (b), e.g. if the Store is created with `optimize_scalar=False`, and (b) can happen without (a), e.g. if a Future-backed scalar array is broadcasted to a larger volume.

Formalize "scalar" property on Stores

---

install.py

This PR is to use the `control_replication` branch as the default Legion branch for all our development work so that we can keep `legate_stable` really stable. The install script now checks if we're on one of the development branches (i.e., we're not on either `main` or `master`) and if so, picks `control_replication` and `legate_stable` otherwise. The script will need to be updated once `control_replication` in Legion is merged with the `master`.

Switch the default Legion branch to control_replication

---

legate/core/launcher.py
legate/core/operation.py
legate/core/runtime.py
legate/core/solver.py
legate/core/store.py
src/core.mk
src/data/store.cc
src/data/store.h
src/data/store.inl
src/legate_c.h
src/mapping/mapper.cc
src/runtime/context.cc
src/runtime/context.h
src/runtime/runtime.cc
src/task/return.cc
src/task/return.h
src/task/task.h
src/utilities/deserializer.cc
src/utilities/deserializer.h
src/utilities/machine.cc
src/utilities/machine.h

This PR is to revise the task wrapper for scalar outputs in order to insulate client libraries from legate stores' underlying storage (i.e., whether they are future-backed or region-backed). We will also allow legate tasks to return multiple scalar outputs with this PR.

Refactor the task wrapper for scalar outputs

---

legate/core/operation.py
legate/core/solver.py
legate/core/utils.py

With non-deterministic iteration orders we may end up emitting
runtime calls in a different order on different shards, thus
causing control replication violations.

Use data structures with deterministic iteration order in the solver

---

legate/core/store.py
legate/core/transform.py
src/data/transform.cc

This PR includes a fix for a bug that was converting a domain with a transformation stack in an incorrect order. This also has a change to raise a more informative error message when someone tries to create a slice that corresponds to a non-contiguous subset of a store.

Fixes for transformations

---

legate.py

This PR rearranges user flags for the launcher so that they come last in the command. This allows them to override the values chosen by the launcher.

Rearrange user flags

---

src/core/data/scalar.cc
src/core/data/scalar.h
src/core/data/scalar.inl

This PR adds a code path to `Scalar` to allow scalars to own buffers.

Allow scalars to own buffers

---

legate/core/constraints.py
legate/core/context.py
legate/core/operation.py
legate/core/partition.py
legate/core/solver.py
src/core/mapping/base_mapper.cc
src/core/mapping/base_mapper.h
src/core/mapping/mapping.cc
src/core/mapping/mapping.h
src/core/mapping/task.cc

This PR includes two changes: 1) support for affine image partitions, and 2) a mapper update for store colocation.

Support for affine images and store colocation

---

legate/core/constraints.py
legate/core/operation.py
legate/core/runtime.py
legate/core/solver.py

This is the same as #84, but rebased on `branch-22.01`.

Object cycle fix ported to branch-22.01

---

legate.py

The probe is disabled by default, so it won't conflict with Realm's memory reservations. It is, therefore, safe to set GASNET_PHYSMEM_MAX to a large value, and Realm will do this internally if we don't set it manually.

Realm now sets GASNET_PHYSMEM_PROBE/MAX internally

---

legate/core/io.py

This PR is to use `itertools.product` instead of `math.prod`, as the latter is available only in Python >= 3.8 and we haven't bumped up the supported Python version yet.

Replace math.prod with itertools.product

---

legate/core/__init__.py

Add support for a nice error message when users try to use legate outside of `legion_python`

Fix for Issue 77

---

legate/core/runtime.py

The core wasn't doing anything for deferred detachments sitting in the attachment manager. This PR fixes that issue.

Fix for deferred detachments

---

legate/core/launcher.py
legate/core/operation.py
legate/core/store.py

This PR fixes two issues: 1) the launcher wasn't tagging a store promoted from another future-backed store as a future-backed store; 2) `set_storage` wasn't updating the parent's storage, leading to a bi-furcation.

Fix for `set_storage`

---

install.py

In `find_active_python_version_and_path` function, the `p.replace(".a", ".dylib" if os_name == "Darwin" else ".so")` will lead to the bug if the directory path including the `.a` substring, e.g. `/home/software.ihep.ac.cn/python/libxxx.a` will be replaced with 
`/home/software.ihep.soc.cn/python/libxxx.so`, therefore a simple fix for this bug.

bug fix in install.py

---

src/core/runtime/runtime.cc
src/core/runtime/runtime.h
src/core/task/task.h

This PR adds an environment variable through which users can run the code with empty tasks. This is going to be useful to study the runtime overhead.

Flag to use empty tasks

---

legate/core/constraints.py
legate/core/operation.py
legate/core/solver.py

With this PR, both `add_broadcast` and `PartSym.broadcast` take axes that should not be partitioned.

Support for partial broadcasting

---

install.py

This PR is to make sure the NCCL configuration used in the core build is exported so that other Legate libraries can refer to it.

Build update

---

src/legate.mk

This PR contains changes to support offline device linking. From now on, any CUDA source files for device linking need to be added to `GEN_DEVICE_SRC` and linker flags for the device linking can be passed via `DEVICE_LD_FLAGS`.

Support for offline device linking

---

legate/core/operation.py

This PR adds some well-formedness checks for both normal and indirect copies. This also fixes a bug in the logic that adds constraints for normal copies.

Safety checks for copies

---

src/core/mapping/base_mapper.cc
src/core/mapping/base_mapper.h

This PR is to correctly distribute manually parallelized tasks having no store arguments.

Mapper fix for tasks with no store arguments

---

.gitignore
legate/core/legion.py
legate/core/projection.py
legate/core/utils.py

I did not realize Python 3.7 is not currently run in CI. Many thanks to @manopapad for noticing that there were issues in 3.7 due to `__future__` features unintentionally being used outside annotation contexts in a few places. The PR fixes those up, with TODOs for later. I have installed everything and run tests in a 3.7 env and will continue to develop under 3.7 for the time being. cc @magnatelee

Quickfix: Fix non-annotations on 3.7

---

conda/core_dev.yml
legate/core/_legion/transform.py
legate/core/context.py

This PR bumps up the minimum NumPy version to 1.22 and removes code that becomes obsolete due to that change.

Bump up NumPy version

---

legate/core/runtime.py

The core runtime hangs in the prime factorization when the number of usable processors is 0. This PR instead raises an exception when that happens.

Raise an exception if there's no usable processor

---

src/core.mk
src/core/comm/comm_nccl.cu
src/core/task/task.h
src/core/utilities/nvtx_help.h

This PR makes an initial effort to integrate NVTX in Legate core. This creates an NVTX ranges for each task invocation, and with #208, the range can optionally represent the task's total execution time.

NVTX integration

---

src/core/cuda/cuda_help.h

Some compilers don't seem to find `stderr` and `fprintf` when `cuda_help.h` is included.

Fix compile issue with cuda_help.h

---

conda/conda-build/build.sh

Updates build.sh with:
1) Set the std to c++17 to fix the type_traits templating issue
2) Builds up the install arguments in a variable and comments on each addition
3) Adds an install argument to target the CPU feature set equivalent to haswell

Update build.sh with specific CPU targeting

---

legate/core/constraints.py
legate/core/launcher.py
legate/core/operation.py
legate/core/shape.py
legate/core/transform.py

`Protocol` and `overload` are available in stdlib `typing` in Python>=3.8 so there is no need to use `typing_extensions` for them.
https://docs.python.org/3.8/library/typing.html

Use stdlib typing where possible

---

legate.py

This PR introduces two new launcher flags for Nsight:
* `--nsys-targets`: takes a comma-separated list of APIs to trace with Nsight. The default is `cublas,cuda,cudnn,nvtx,ucx`.
* `--nsys-extra`: can be used to specify extra flags to pass to Nsight. More than one `--nsys-extra` can be used. For example, `--nsys-extra=-s --nsys-extra=cpu` enables CPU sampling.

Launcher flags to configure Nsight Systems

---

legate/core/_legion/__init__.py
legate/core/_legion/field.py
legate/core/_legion/operation.py
legate/core/_legion/space.py
legate/core/_legion/util.py

The unordered field destruction turns out to have been broken when legion.py was refactored. This PR fixes the issue, and also fixes another minor typing issue.

Fix unordered field destruction

---

install.py
scripts/lgpatch.py

This PR adds a wrapper for legate that can patch specified libraries and then execute a given script with those patches already in place.
```
~/work/legate.core bryanv/zcc
dev38 ❯ lgpatch.py test.py -patch numpy -cunumeric:report:coverage
cuNumeric API coverage: 4/4 (100.0%)
```
See below for `test.py` example script that only imports numpy. 
* Is `scripts/lgpatch.py` the best place/name for this? Should it be installed (as `lgpatch`?) in the install bin directory?
* Is `-patch:help` suffient for help? Legate intercepts `-h` and `--help` before we can get to them so we can't use those. 
* This does not use the trivial `cunumeric.patch()` because I wanted to have more error checking. But we could move that to `patch` and simplify here if desired (but then every new lib would be responsible …

Add script wrapper for zero code-change patching

---

src/core/data/store.cc
src/core/data/store.h

Legate stores were returning type codes in `LegateTypeCode`, but stores can use client specific types. This PR addresses the issue and makes `code()`  a template function so client libraries can override the type code types.

Use 32-bit integers for type codes

---

legate/core/_legion/operation.py
legate/core/launcher.py
legate/core/operation.py

Legate core was using write-discard privilege for scatter targets, which make them not fetch valid values for pass-through entries. This PR is to fix that issue.

Use read-write privilege for scatter targets

---

src/core/legate_c.h

Add `#include` directives for `legion_config.h` and `cstdint`. This ensures `legate_c.h` can be included from other C++ headers without respect to other `#include` directives, and aids intellisense providers (like `clangd`) who infer the compile commands from the C++ build.
Related to:
* https://gitlab.com/StanfordLegion/legion/-/merge_requests/498

Add missing includes to aid intellisense providers

---

legate/core/launcher.py
legate/core/types.py

This seems to be correct since `bool` is passed in, rather than a boolean value. Evidently it was not exercised until some `cunumeric`, where these mypy errors surfaced:
```
dev38 ❯ mypy ../legate.core/install38/lib/python3.8/site-packages/legate /home/bryan/work/legate.core/typings/ cunumeric
cunumeric/linalg/cholesky.py: note: In function "tril":
cunumeric/linalg/cholesky.py:167:31: error: Argument 2 to "add_scalar_arg" of "Task" has incompatible type "Type[bool]"; expected "Union[bool, DataType]"  [arg-type]
task.add_scalar_arg(True, bool)
^
cunumeric/linalg/cholesky.py:170:31: error: Argument 2 to "add_scalar_arg" of "Task" has incompatible type "Type[bool]"; expected "Union[bool, DataType]"  [arg-type]
```

Minor type fix

---

conda/conda-build/build.sh
src/Makefile

The -lcuda link flag in legate.core is superfluous, and the Legion
build, where -lcuda is necessary, adds the original stubs directory
automatically.

Conda build doesn't need to mess with CUDA stubs

---

legate/core/context.py

Quick PR to provide wrappers `create_auto_task` and `create_manual_task` for the generic `create_task`. This affords cleaner type resolution in client libraries. 
I did not make `create_task` private for now, to avoid disturbing `cunumeric` existing usage, but it could be considered in the future if desired.
I did also try to solve this using `@overload` instead, which would have improved things for existing `create_task`, at least when bool literals were passed. But overloading a non-first optional arg seems more than mypy can handle.

Split create_task

---

src/core/comm/coll.cc

I had a case that GASNet will crash if I finalize the MPI in the `collFinalize` function, so we will just let GASNet to handle the initialization and finalization of MPI.

let gasnet to handle mpi init and finalize

---

src/core/comm/coll.h
src/core/comm/pthread_barrier.h

This commit adds a dummy implementation of pthread_barrier for Mac OS
since it does not support pthread_barriers. This is necessary for
performing builds on Macs without MPI.

src/core/comm: add simple implementation of pthread_barrier for mac

---

src/core/comm/coll.cc

I used to get the address of a vector element and assign it to Communicator of each rank, but this is wrong, because vector is a dynamic data structure,  when it is resized, the address can be changed.

fix the coll for non-mpi case.

---

install.py

Until we add the required special-casing to the legate driver script for
launching under the UDP conduit.

Temporarily drop support for UDP conduit

---

legate/core/launcher.py
legate/core/operation.py

Original type for `add_scalar_arg` was too narrow, discovered in https://github.com/nv-legate/cunumeric/pull/438

Broaden add_scalar_arg type

---

.pre-commit-config.yaml
legate/core/corelib.py

This PR adds a [pre-commit hook for mypy](https://github.com/pre-commit/mirrors-mypy). It should run `mypy legate` whenever there are relevant file changes.

add mypy pre-commit hook

---

src/core.mk
src/core/comm/coll.h

This commit switches the relative include of "pthread_barrier.h" to an
absolute path off of core/ so that client libraries that include
"core/comm.h" can find the file.

src: switch to abolute include path for pthread_barrier.h

---

src/core/mapping/base_mapper.cc

Now GPU tasks reading futures won't block on this transfer mid-execution

Fix target_memory setting for task futures

---

src/core/mapping/base_mapper.cc

Now GPU tasks reading futures won't block on this transfer mid-execution
Co-authored-by: Manolis Papadakis <mpapadakis@nvidia.com>

Fix target_memory setting for task futures (#327)

---

legate/core/runtime.py

in the case when array of zero size is passed to the task, we would like to skip partitioning (e.g when array of shape like (0,3) is passed)

fix partitioning of empty regions

---

legate/core/store.py
legate/core/transform.py
src/core/data/store.inl
src/core/data/transform.cc

The inline mapping code had been crashing when the store was 0D. This PR fixes that bug.

Correctly inline map 0d stores

---

legate.py

This option has been replaced by the CUNUMERIC_PEDANTIC_MATH
environment variable.

Remove deprecated option --no-tensor

---

legate/core/communicator.py

Fix the hang of destroy of CPU communicators.
To destroy a communicator, `collCommDestroy` needs to be called by all ranks within the communicator CONCURRENTLY, so we need to make sure communicators are destroyed one by one, otherwise, we may run out of the CPUs to make sure all ranks call `collCommDestroy` concurrently.

make sure communicators are destroyed one by one

---

legate/core/operation.py
src/core/comm/comm_cpu.cc
src/core/mapping/base_mapper.cc
src/core/mapping/core_mapper.cc
src/core/runtime/runtime.cc
src/core/task/task.cc
src/core/task/task.h

This PR is to specify an upper bound for return value sizes for `core::extract_scalar`. This also includes a minor optimization for the demux logic that treats future maps of size 1 as futures.

Specify an upper bound for return value sizes for `core::extract_scalar`

---

src/core/mapping/base_mapper.cc
src/core/mapping/base_mapper.h
src/core/mapping/instance_manager.cc
src/core/mapping/instance_manager.h

Mappers used separate instance managers, which prevented them from reusing instances created by others. This PR fixes that problem simply by sharing the same instance manager with all Legate mappers.
Update: this PR has been updated to contain changes from #351 and other improvements to the instance manager.

Instance manager improvements

---

.github/workflows/require-labels.yml

Exactly one of the `category` labels is required. Categories are:
- a bug fix (`category:bug-fix`)
- an improvement (`category:improvement`)
- a new feature (`category:new-feature`)
- a task (`category:task`)
The labels will be used to automatically generate release notes. A task is the only label that will cause a PR not to appear in the release notes.

Require labels on pull requests

---

src/core/mapping/base_mapper.cc
src/core/mapping/instance_manager.cc
src/core/mapping/instance_manager.h

#350 used `std::mutex` to synchronize accesses to the shared instance manager, which turns out to be problematic as the blocking behavior is invisible to the runtime and eventually leads to hangs. This PR replaces that mutex with Legion's locking mechanisms that are compatible with the runtime's thread management.

Use Legion primitives to coordinate accesses to the shared instance manager

---

src/core/runtime/context.cc
src/core/runtime/context.h
src/core/runtime/runtime.cc
src/core/runtime/runtime.h

This PR adds a new shell variable `LEGATE_LOG_MAPPING` that produces detailed logging on mapping decisions when set.

Support for mapper logging

---

src/core/mapping/core_mapper.cc
src/core/task/return.cc

This PR fixes a compile issue in cpu-only build introduced by #353 and also maps future map reductions back to CPU for performance reasons.

Follow-on changes to #353

---

src/core/mapping/core_mapper.cc

The precise stacktrace capturing seems to be causing all sorts of confusion and problems as it's been turned on by default in debug mode. This PR requires it to be explicitly requested.

Turn off the precise stacktrace capturing by default

---

legate.py
legate/core/launcher.py
legate/core/store.py

Scalar stores didn't work correctly if they were passed as inout arguments (i.e., when the same scalar store is passed as both an input and an output). This PR fixes the issue.

Scalar store fix

---

src/core/mapping/instance_manager.cc

Fixes various segfaults in the InstanceManager, and strengthens the sanity checks.
The subsumption checks are no longer used, and can be removed if there is no further need for them.

InstanceManager segfault fixes

---

.github/workflows/require-labels.yml

When a PR is created, the authors will often set the labels soon after creation. We will have a "grace period" on a new pull request to allow setting labels after the PR is created.

Delay label checking on fresh PRs

---

legate/core/runtime.py

PR #364 accidentally removed the heuristic that issues consensus matches more frequently for bigger fields. This PR recovers that heuristic in the form of match credits: Each field manager is now assigned a credit based on its size. Whenever a new free field arrives at the field manager, it adds its credit to the match manager's counter. When the counter exceeds a threshold, the match manager issues a consensus match.

Adjust consensus match frequency based on field sizes

---

legate/driver/driver.py
tests/unit/legate/driver/test_driver.py

closes #401 
tests:
```
bldtest ❯ pt tests/unit/legate/driver -v -k test_verbose_nonero_rank_id
=================================================== test session starts ===================================================
platform linux -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0 -- /home/bryan/anaconda3/envs/bldtest/bin/python
cachedir: .pytest_cache
rootdir: /home/bryan/work/legate.core
plugins: mock-3.8.2, cov-3.0.0, lazy-fixture-0.6.3
collected 1046 items / 1042 deselected / 4 selected                                                                       
tests/unit/legate/driver/test_driver.py::TestDriver::test_verbose_nonero_rank_id[OMPI_COMM_WORLD_RANK] PASSED       [ 25%]
tests/unit/legate/driver/test_driver.py::TestDriver::test_verbose_nonero_rank_id[PMI_RANK] PASSED …
```

Driver verbose only for rank 0 or "none" launcher

---

legate/util/args.py
tests/unit/legate/util/test_args.py

fixes #415 
@rohany can you check out this PR branch and confirm it fixes the issue for your use case? Seems to for me:
```
~/work/legate.core bv/short_arg_conflicts*
dev38 ❯ cat ~/tmp/foo.py 
import legate.core
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("-l", type=int, default=None)
args, _ = parser.parse_known_args()
print(args.l)
~/work/legate.core bv/short_arg_conflicts*
dev38 ❯ legate --rlwrap  ~/tmp/foo.py -l 5 
5
```

Handle conflicts for library-level args

---

legate/core/runtime.py
src/core/mapping/core_mapper.cc

Fixes #407. The code was allowing field managers to create fields on dead region managers (i.e., those kept in the LRU queue) and when those fields are gc'ed, they "double free" their region managers. This PR fixes the problem by reviving dead region managers upon fresh field allocations.
Since this is a critical bug fix, this needs to be merged with `branch-22.10` first and ported to `branch-22.12`.

Revive dead region managers on field allocations

---

src/core/mapping/base_mapper.cc
src/core/mapping/base_mapper.h

On mapping failure retry after tightening non-RO reqs

---

legate/util/fs.py
tests/unit/legate/driver/test_main.py

A call to `read_cmake_cache_value` in an `except` block could itself also raise an exception, this needed to be guarded against.

Fix an issue with editable installs

---

legate/tester/stages/util.py
legate/util/ui.py
tests/unit/legate/tester/stages/test_util.py
tests/unit/legate/util/test_ui.py

This PR adds explicit reporting of `pytest.main` exit codes on failure, since there are currently some cases where all individual tests are passing, yet the process is failing overall. 
Looks like:
```
[FAIL] (Eager) tests/integration/test_slicing.py (exit: 1) 
```
ref: https://docs.pytest.org/en/stable/reference/exit-codes.html

Report pytest exit code on fail

---

legate/driver/args.py
legate/driver/config.py
legate/jupyter/args.py
legate/jupyter/config.py
legate/tester/args.py
legate/tester/config.py
legate/util/colors.py
tests/unit/legate/driver/test_config.py
tests/unit/legate/jupyter/test_config.py
tests/unit/legate/tester/test_config.py
tests/unit/legate/util/test_colors.py

The current terminal colors are not good on light terminal backgrounds. A real solution to this would require "themes" (at least light and dark). For now, make terminal colors explicitly opt-in via a `--color` command line arg, even if `colorama` is installed.
I don't love the implementation here, but it will do for now. If we really want to improve this, we can address that at that time. But if we want to really improve things I would probably advocate for taking on [`rich`](https://github.com/Textualize/rich) as a dependency and jettisoning all my simplistic TUI code.

Make terminal colors explicitly opt-in

---

.github/workflows/ci.yml

v2 -> v3 to avoid GitHub warnings.

Update upload artifact action version

---

bind.sh
legate/driver/command.py
tests/unit/legate/driver/test_command.py

This PR changes the driver invocation to always add `bind.sh` unconditionally. This is so that a computed `LEGATE_RANK` environment variable can be set consistently, regardless of launch presence or kind. This will support a future PR that adds an option for per-rank Python cprofile output.
The new usage for `bind.sh` is:
```
bind.sh --launcher <launcher> [--cpus <spec>] [--gpus <spec>] [--mems <spec>] [--nics <spec>] -- <app> ...
```
The main differences are:
* `--launcher` required before the launcher value (`local`, `mpirun`, `srun`, or `jsrun`)
* delimeter `--` required before remaining "app" portion
These changes make the reported invocation less confusing and more robust, and should be fine since `bind.sh` is only invoked by the driver, and the driver has complete control over the …

Call bind.sh unconditionally

---

legate/core/types.py

legate/core/types: add missing `to_pandas_type` on Complex types

---

src/core/comm/coll.cc

If `-ll:networks none` is passed, then GASNet will not be initialized, in this case, we will init the MPI explicitly.

fix for -ll:networks none, we will init MPI if it has not been initialized

---

legate/tester/__init__.py
legate/tester/stages/test_stage.py

This PR adds a test config 
```
CUSTOM_FILES: list[CustomTest] = [
CustomTest(
"tests/integration/test_swapaxes.py", "cuda", ["--fbmem", "8192"]
)
]
```
That can be used to have customized test invocations (per-stage) that override normally computed shard options. Customized tests (if they are present) are executed in serial after all the normal test stage invocations.
@manopapad can see example custom test in https://github.com/nv-legate/legate.core/pull/469/commits/68a35f385840b0d6523b8c62f6b2ee9c53305a67

Add option to have per-file, per-stage test overrides

---

bind.sh
legate/driver/args.py
legate/driver/command.py
legate/driver/config.py
legate/driver/driver.py
legate/driver/launcher.py
legate/driver/logs.py
legate/jupyter/config.py
tests/unit/legate/driver/test_args.py
tests/unit/legate/driver/test_command.py
tests/unit/legate/driver/test_config.py
tests/unit/legate/driver/test_launcher.py
tests/unit/legate/jupyter/test_config.py

This PR updates the driver to do all rank detection in `bind.sh`. This affects the current `nvprof` and `nsys` options. Once the PR is tested on a real cluster and merged, I will make a follow-on PR to add `cprofile` option that uses the same. 
This PR also adds a driver option `--bind-detail` to the option (and corresponding `--debug` option to `bind.sh`) that will show exactly what invocation `bind.sh` ends up calling. It can be used with `--verbose` and tests, to see what ultimately gets executed, e.g. 
```
+LEGATE_TEST=1 CUNUMERIC_MIN_CPU_CHUNK=2000000000 CUNUMERIC_MIN_OMP_CHUNK=2000000000 CUNUMERIC_MIN_GPU_CHUNK=2000000000 legate /home/bryan/work/cunumeric/tests/integration/test_2d_reduction.py --cpus 1 --cpu-bind 3,9 -v --bind-detail
[PASS] (Eager) …
```

Use bind.sh for all rank detection

---

conda/conda-build/build.sh

It is hard to determine how much of a conda build is the conda overhead, and how much is the actual build time. These printouts make it possible to check that.

Print build start and end times in a conda build

---

install.py

Previously we would pass this setting through an envvar in quickstart build.sh, but Legion's cmake workflow overrides this value, so we need to pass it as a cmake flag.

Pass a sufficiently high default value for gasnet's ibv-max-hcas

---

bind.sh
legate/driver/args.py
legate/driver/command.py
legate/driver/config.py
legate/jupyter/config.py
tests/unit/legate/driver/test_command.py
tests/unit/legate/driver/test_config.py
tests/unit/legate/jupyter/test_config.py

This PR adds a new option `--cprofile` to the driver that enables the Python stdlib `cProfile` module. 
The `cProfile` module must be loaded with that  `-m` python (legate) command line option. This PR handles things in `cmd_module` function that normally handles `--module`, in order to make an explicit exception if `--cprofile` is used together with `--module` (i.e. they are incompatible)
The cprofile output is stored at
```
config.logging.logdir / f"legate_{LEGATE_GLOBAL_RANK_SUBSTITUTION}.cprof"
```
so that multi-rank profiling is possible.

Add --cprofile driver option

---

legate/core/runtime.py
src/core/runtime/runtime.cc
src/core/task/return.cc
src/core/task/return.h
src/core/task/task.h

The `extract_scalar` task was deserializing the packed scalar buffer into individual scalars when it needed to extract one of them. This PR optimizes the operation to be constant-time.

Optimize scalar extraction

---

CMakeLists.txt
cmake/generate_install_info_py.cmake
legate_core_python.cmake
scripts/build-install.sh
scripts/build-no-install.sh
scripts/build-separately-no-install.sh
scripts/build-with-legion-no-install.sh
scripts/build-with-legion-separately-no-install.sh

This PR adds a custom target to generate `install_info.py` on every build, not just the initial configure.
```shell
$ ninja -C legate.core/_skbuild/linux-x86_64-3.9/cmake-build/
ninja: Entering directory `core/_skbuild/linux-x86_64-3.9/cmake-build/'
[2/2] Generate install_info.py
```

Regenerate `install_info.py` on every build

---

legate/core/communicator.py

This commit fixes the following leak, leading to shutdown hangs.
```
found cycle!
tail:
0x200092ca1e10: <class 'legate.core._legion.future.FutureMap'>
^
0x200058dd65c0: <class 'dict'>
^ ["_handles"]
0x2000588dff80: <class 'dict'>
^ .__dict__
0x2000889b11b0: <class 'legate.core.communicator.NCCLCommunicator'>
^ ["_nccl"]
0x2000588dd540: <class 'dict'>
^ .__dict__
0x2000887b8430: <class 'legate.core.runtime.CommunicatorManager'>
^ ["_comm_manager"]
0x2000889f7d00: <class 'dict'>
^ .__dict__
0x2000887b9f90: <class 'legate.core.runtime.Runtime'>
^ ["runtime"]
0x200173d7b180: <class 'dict'>
cycle:
0x200173d7b180: <class 'dict'>
^ .__dict__
0x200173d84370: <class 'legate.core.runtime.ConsensusMatchingFieldManager'>
^ ["manager"]
0x200173e30cc0: <class 'dict'>
^ .__dict__
0x200173db2e00: <class …
```

legate/core: fix FutureMap leak in communicator shutdown

---

legate/core/runtime.py

This allows for users of `reset_key_partition()` not need to query if there is a key partition already -- slightly more ergonomic use.

legate/core: guard deletion in reset_{store,storage}_key_partition

---

legate/driver/config.py
tests/unit/legate/driver/test_command.py
tests/unit/legate/driver/test_config.py

In the interest of making future example in docs as clean and unconfusing as possible, this PR removes the "nocr fixup" for single node console usage, where it is not needed, so that users are not confronted by a WARNING that does not apply and that they may not understand.

Don't nocr for single node

---

legate/jupyter/kernel.py

This small PR fixes the uninstall instructions when a duplicate kernel name is attempted to install.  `KernelSpecManager` calls `lower` on kernel names before saving them out, so the command is, e.g 
```
jupyter kernelspec uninstall legate_sm_gpu           
``` 
and not
```
jupyter kernelspec uninstall 'Legate_SM_GPU'
```
even if the original kernel name was "Legate_SM_GPU".

Fix uninstall instructions for jupyter extension

---

install.py

Will need to revert this PR once `collective` is merged with `control_replication`.

Change the default Legion branch to collective

---

legate/core/projection.py
legate/core/transform.py
src/core/runtime/projection.cc

This PR makes two changes to the projection functor code:
* Delinearizing functor is now an instance of LegateProjectionFunctor so we can derive a sharding functor from it
* Projection functor creations and queries are now logged. Debugging code that renders projection functors is also improved.

Sharding functor for delinearizing functor

---

scripts/generate-conda-envs.py

If os is specified as `osx` nothing is generated, and if os is specified as `darwin` then input validation throws an error.
Solve this by replacing input ostype as darwin.

Update env gen script so OS type works for mac

---

legate/driver/launcher.py

This PR removes the check on `REALM_PYTHON_LIB` per:
> realm no longer hardcodes a full path, so someone needs to make sure that libpython.so can be found at runtime through normal .so loading procedures

Remove realm pylib check

---

src/core/data/store.cc
src/core/mapping/base_mapper.cc
src/core/mapping/core_mapper.cc

This PR is a companion to #518 to make sure futures are mapped to zero-copy unless requested otherwise.

More changes to map futures to zero-copy memory

---

src/core/mapping/base_mapper.cc

Otherwise a program like this:
```
M1 = cn.ones((30,30))
M2 = cn.ones((30,30))
M3 = M1.dot(M2)
```
produces this warning:
```
Ignoring request by mapper cunumeric on Node 0 to check for collective usage for region requirement 2 of task cunumeric::MatMulTask (UID 159) because region requirement has writing privileges
```

Don't check for collective behavior when we have WRITE privilege

---

src/core/mapping/base_mapper.cc
src/core/mapping/instance_manager.cc
src/core/mapping/instance_manager.h

Currently, the instance manager never removes its cached instances even when they cannot be acquired. This makes the base mapper forever attempt to reuse instances that cannot be acquired. This PR fixes the problem.

Erase cached reduction instances that cannot be acquired

---

install.py

Change the default architecture to haswell. Currently, we build our conda packages with haswell to avoid compatibility issues. Changing the default architecture to haswell will make default builds comparable to the conda packages and it will allow developers to share sccache with CI builds.

Change the default CPU architecture to haswell.

---

legate/__init__.py
legate/args.py
legate/core/runtime.py
legate/driver/args.py
legate/rc.py

This PR adds support for displaying help for command line options for downstream legate libraries such as  `cunumeric` (ref: https://github.com/nv-legate/cunumeric/pull/755).  
Known libraries are speculatively imported, and in case the downstream libraries are not "plain-python" importable (as would be the case in the driver) an environment variable is first set that can be used to condition the library's top-level import. This is clunky, but is only utilized in `print_help` which is called only before immediate program exit. 
```
dev310 ❯ legate --help
usage: legate [-h] [--nodes NODES] [--ranks-per-node RANKS_PER_NODE] [--no-replicate] [--launcher {mpirun,jsrun,srun,none}] [--launcher-extra LAUNCHER_EXTRA] [--cpu-bind CPU_BIND] [--mem-bind MEM_BIND]
<<<<< SNIP >>>>>
Other options: …
```

CLI help for library options

---

conda/conda-build/build.sh

This reverts commit 6c718de3c7a986a8a5003d0964dfcc810756bc6b. We will support Hopper in the next release.

Revert "Update the architectures built in conda package (#545) (#546)"

---

install.py
legate/driver/driver.py

This PR adds a `Versions:` section to the `-legate -verbose` output, that reports `legate` and (if found) `cunumeric` version information. Future work will add `legion` version information. 
This PR uses the recent work to make `cunumeric` top-level importable for purposes of scraping metadata from the package.

Report version info in --verbose outupt

---

src/core/runtime/runtime.cc
src/core/utilities/nvtx_help.h

This branch makes two changes:
- Replaces the use of the nvtxRangeStart/RangeEnd API with RangePush/RangePop
- Tags NVTX events with a domain specific to legate.core for easy filtering

NVTX: Use RangePush and Domain

---

legate/core/__init__.py
legate/driver/__init__.py
legate/driver/args.py
legate/driver/config.py
legate/tester/stages/_linux/cpu.py
legate/tester/stages/_linux/eager.py
legate/tester/stages/_linux/gpu.py
legate/tester/stages/_linux/omp.py
legate/tester/stages/_osx/cpu.py
legate/tester/stages/_osx/eager.py
legate/tester/stages/_osx/gpu.py
legate/tester/stages/_osx/omp.py
legate/tester/stages/test_stage.py
tests/unit/legate/tester/stages/_linux/test_cpu.py
tests/unit/legate/tester/stages/_linux/test_gpu.py
tests/unit/legate/tester/stages/_linux/test_omp.py
tests/unit/legate/tester/stages/test_test_stage.py

This PR adds support for `LEGATE_CONFIG` as a mechanism for supplying legate or legion configuration options. Other points:
* The `legate` driver now recognizes a script and its arguments more generally by using all of the "remaining" args, rather than assuming a `.py` file extension somewhere.
* The `legate` driver still supports passing ***Legate*** (only) command line options before a script to run. The driver is an application, and it is reasonable for an application to process its own arguments since it can control when that processing happens. 
Broadly speaking, these two usages are what is now possible:
```
LEGATE_CONFIG="legate or legion opts" legate <legate opts only> <script> <script or legion opts>
LEGATE_CONFIG="legate or legion opts" python <script> <script opts>
``` …

Args and Config

---

BUILD.md

Rust was added to the build tools in PR #535, but BUILD.md has not been updated yet.
Signed-off-by: OTABI Tomoya <tomoya.otabi@gmail.com>

Update Build.md to add the missing dependency, rust

---

src/core/mapping/base_mapper.cc

This PR fixes an intermittent segfault in `legate_select_sources`.

Mappers should skip collective views with no suitable instance

---

legate/core/__init__.py

fixes #568 
With this PR:
```
dev310 ❯ python -c "import legate.core; import sys; print(sys.argv)" --foo
['-c', '--foo']
```

don't use sys.argv for plain python init

---

legate/driver/args.py
legate/settings.py
legate/tester/stages/_linux/cpu.py
legate/tester/stages/_linux/eager.py
legate/tester/stages/_linux/gpu.py
legate/tester/stages/_linux/omp.py
legate/tester/stages/_osx/cpu.py
legate/tester/stages/_osx/eager.py
legate/tester/stages/_osx/gpu.py
legate/tester/stages/_osx/omp.py
legate/tester/stages/test_stage.py
legate/tester/stages/util.py
legate/util/args.py
tests/unit/legate/tester/stages/_linux/test_cpu.py
tests/unit/legate/tester/stages/_linux/test_eager.py
tests/unit/legate/tester/stages/_linux/test_gpu.py
tests/unit/legate/tester/stages/_linux/test_omp.py
tests/unit/legate/tester/stages/test_test_stage.py
tests/unit/legate/util/test_args.py

This PR closes the loop with #567 and https://github.com/nv-legate/cunumeric/pull/799 
* Updates tester to set `CUNUMERC_TEST=1` instead of passing `-cunumeic:test`
* Removes argparse feature for help with library command line args (and also removes janky conditional imports)

Updates for cmd opts -> env vars

---

legate/tester/__init__.py
legate/tester/args.py
legate/tester/config.py
legate/tester/stages/_linux/omp.py
tests/unit/legate/tester/stages/_linux/test_omp.py
tests/unit/legate/tester/test___init__.py
tests/unit/legate/tester/test_args.py

This PR adds `--numamem` to the tester so we can run tests with numa memory as before. (See the test driver failure: https://github.com/nv-legate/cunumeric/actions/runs/4191696755/jobs/7268552774)

Add `--numamem` to the tester

---

legate/_sphinxext/__init__.py
legate/_sphinxext/settings.py
pyproject.toml
scripts/generate-conda-envs.py

This PR:
* Adds `nbsphinx` and friends to support rendering notebooks in the docs
* Adds a sphinx directive to documeting `Settings` objects (see https://github.com/nv-legate/cunumeric/pull/805) 
@marcinz we still need to update dependencies on gitlab, also, is that correct?

Deps for cunumeric docs updates

---

src/core/runtime/runtime.cc
src/core/utilities/nvtx_help.h

One side-effect of #293 is that NVTX ranges are now associated with physical thread ids in Nsight. This is undesirable at the moment, as each GPU processor is currently rendered as multiple threads in Nsight (an issue that @manopapad and I are still investigating) and thus the ranges now spread across those threads. Even worse is that since each thread only has ~20 boxes to show, rendering is suppressed for them, as I guess they are seemingly uninteresting. Until we fix this behavior, we will fall back to the old code for NVTX ranges, which at least shows all the ranges on a single line.
cc @evanramos-nvidia @manopapad

Revert "NVTX: Use RangePush and Domain (#293)"

---

conda/conda-build/meta.yaml

While trying to debug the CI, my local build hit the following from legion/realm compilation:
```
[35/197] Building CXX object _deps/legion-build/runtime/CMakeFiles/RealmRuntime.dir/realm/cuda/cuda_module.cc.o
FAILED: _deps/legion-build/runtime/CMakeFiles/RealmRuntime.dir/realm/cuda/cuda_module.cc.o
$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ -DRealmRuntime_EXPORTS -I$PREFIX/include -I$SRC_DIR/build/_deps/legion-src/runtime -I$SRC_DIR/build/_deps/legion-build/runtime -UNDEBUG -march=haswell -O2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Woverloaded-virtual -std=gnu++17 -MD -MT _deps/legion-build/runtime/CMakeFiles/RealmRuntime.dir/realm/cuda/cuda_module.cc.o -MF _deps/legion-build/runtime/CMakeFiles/RealmRuntime.dir/realm/cuda/cuda_module.cc.o.d -o …
```

Add nvml dependency in the conda build script to get the headers for realm

---

legate/driver/command.py
legate/install_info.py.in
legate_core_python.cmake
tests/unit/legate/driver/test_command.py

This PR adds runtime detection of the Realm network (thanks to @trxcllnt for pointing me in a simpler direction than I was originally looking), exposed as a list `install_info.networks` 
Additionally, the options for `bgwork` and `bgworkpin` have been factored into their own `cmd_bgwork`
@manopapad before I add unit tests, one slight difference to clarify: previously, `-ll:bgwork` was *not* added if `utility == 1`. In the current PR, `cmd_bgwork` adds it unconditionally (even if `utility == 1`) Is this correct, or should `cmd_bgwork` retain that same condition?

Runtime network detection and UCX options

---

legate/core/partition.py
legate/core/shape.py

This is the underlying issue behind https://github.com/nv-legate/cunumeric/pull/721#issuecomment-1370307289. Thanks to @aschaffer for doing most of the work to uncover this.
The error in the original logic can be seen when running the following example:
```
import cunumeric as num
a = num.ones((8, 10, 8))
v = num.ones((3, 5, 3))
num.convolve(a, v, mode="same")
```
with `LEGATE_TEST=1 CUNUMERIC_TEST=1 legate --cpus 3 --event --dataflow`, in which case legion spy verification fails with:
```
ERROR: Index Partition: 15 was labelled complete but there are missing points. This is definitely an application bug and invalidates all of Legion's dependence analysis. You must fix this before Legion Spy can continue.
```
The call to `is_complete_for` for the offending partition is misjudging it as …

Fix is_complete_for check

---

src/core/mapping/core_mapper.cc
src/core/mapping/mapping.h

Several fixes.
Correctness:
1. Destructors of top-level class need to be marked virtual
Performance/Best practice
1. Add override to all virtual function implementations
2. Do not mark functions `virtual` that are not intended to have overrides in subclasses, e.g. `CoreMapper`
Style/consistency issues
1. Don't mix `struct` and `class` declarations in a class hierarchy. Subclasses/parent classes should be consistently called `struct` or `class`.  It's better to avoid using `struct` as a way to have methods default public. `struct` often suggests a simply C-style struct while `class` stylistically suggests a non-trivial container with methods.

Fix C++ warnings, virtual destructor bugs, and style issues

---

legate/core/store.py
src/core/runtime/runtime.cc

Global callbacks cannot be labeled static, otherwise the symbol does not get external linkage, and multi-node global `perform_registration_callback` fails with:
```
[1 - 7fbd53fff700]    1.634645 {4}{codetrans}: pointer 0x7fbd361bd7fb in middle of symbol '
[1 - 7fbd53fff700]    1.634738 {6}{runtime}: [fatal 2014] LEGION FATAL: Global registration callback function pointer 0x7fbd361bd7fb is not portable. All registration callbacks requesting to be performed 'globally' must be able to be recognized by a call to 'dladdr'. This requires that they come from a shared object or the binary is linked with the '-rdynamic' flag. (from file /gpfs/fs1/mpapadakis/legion/runtime/legion/runtime.cc:17405)
```
Attaching to NumPy arrays was being done with restricted attachment, which causes errors like: …

Fixes for running cuNumeric CI multi-node

---

legate/driver/command.py

"^dc,ud" will NOT work properly in UCX until 1.14.1 is released. So, for now we need to do it by listing all transports we except dc and ud.

Fix ucx:tls_host default value

---

cmake/thirdparty/get_legion.cmake
legate_core_cpp.cmake

This PR adds the CTK stubs path to implicit link directories in legate's package config, so the stubs path doesn't end up in library consumers' RPATHs.

Add CTK stubs dir to implicit link directories

---

legate_core_cpp.cmake
src/core/runtime/runtime.cc
src/core/runtime/runtime.h
src/core/runtime/runtime.inl

The new registration code was using the same callback to perform all Legate registration callbacks, which accidentally got them deduplicated. This PR fixes the bug by using a function template that will map each Legate callback to a unique Legion callback.

Fix a bug in the new registration callback API

---

legate_core_cpp.cmake

The new `runtime.inl` file was not being installed so this worked on editable builds, but not installed builds

Add missing install file

---

CMakeLists.txt
cmake/thirdparty/get_legion.cmake
cmake/versions.json
install.py

This PR pins the Legion repo URL and git revision that's built if Legion is not found via `find_package()`.
It explicitly ignores values stored in the `CMakeCache.txt`, so subsequent rebuilds that don't set the `--legion-{url,branch}` args revert to the defaults:
```bash
$ install.py --editable --legion-branch "feature_branch"
$ install.py --editable
```

Pin Legion to specific commit sha by default

---

scripts/generate-conda-envs.py

This PR adds gcc/gxx constraints when compilers are requested and CTK <= 11.5
In the current form, the gcc/gxx constraints are added to the "cuda" block in the environment file:
```
- cudatoolkit=11.5
- cutensor>=1.3.3
- nccl
- pynvml
- gcc_linux-64<=11.2
- gxx_linux-64<=11.2
```
The comment headings are only informational, and the constraint is derived from the cuda config, so this seems OK.

Restrict gcc versions to match nvcc compatibility

---

legate/lgpatch.py

fixes #614
This PR improves the `lgpatch` console UX to make it more consistent with the current `legate` driver. Specifically, all `lgpatch` args should come before the program to execute and any of its argument. 
```python
import sys
import numpy as np
print(np.arange(10))
print(sys.argv)
```
Yields
```
docs310 ❯ lgpatch --help
usage: lgpatch [-h] [-p PATCH] [-v] ...
Patch existing libraries with legate equivalents.
Currently the following patching can be applied:
numpy -> cunumeric
positional arguments:
PROG                  The legate program (with any arguments) to run
options:
-h, --help            show this help message and exit
-p PATCH, --patch PATCH
Patch the specified libraries. (May be supplied multiple times)
-v, --verbose         print out more verbose information about …
```

Make lgpatch UX consistent with driver

---

scripts/generate-conda-envs.py

This PR updates `generate-conda-envs.py ` to avoid needing any external dependencies.

Avoid packaging dependency in conda env generate script

---

legate/core/context.py

Follow up to https://github.com/nv-legate/cunumeric/pull/842 this PR removes the generic `create_task` API and leaves only explicit `create_auto_task` and `create_manual_task`

remove generic create_task

---

cmake/versions.json

The release version of Legion needs to be updated to fix issues discovered by QA.

Update Legion SHA (bug fix in Legion)

---

CMakeLists.txt

Switch to rapids-cmake 23.04 early

---

docs/legate/core/source/api/runtime.rst
docs/legate/core/source/conf.py
docs/legate/core/source/index.rst
docs/legate/core/source/versions.rst

This PR makes some small fixes:
* manual `create_task` API needed removing (causing docs build failure)
* terminal copyright date was not correct
* rst file had unusable markdown-style link
Additionally the `conf.py` andindex was cleaned up and made to more closely match the changes that were already made to cunumeric. 
The front page now looks like this:
I do think the "Overview" would be improved if, instead of re-using the README.md, a dedicated `index.rst` was added. cc @magnatelee @manopapad

Docs updates

---

README.md

Temporarily, until we consolidate our documentation

Update info on using standard python interpreter

---

src/core/data/store.cc
src/core/data/store.h
src/core/data/store.inl
src/core/mapping/mapping.cc
src/core/mapping/mapping.h
src/core/runtime/context.cc
src/core/utilities/deserializer.cc
src/core/utilities/deserializer.h

This PR addresses left-over comments from @jjwilke on #563. Functions with confusing/obsolete names are renamed.

Rename variables and functions to make them clearer

---

src/core/mapping/instance_manager.cc
src/core/mapping/mapping.cc
src/core/mapping/mapping.h

The instance manager was checking equality between policies when deciding whether a given instance can be reused. That's overly strict in certain cases and was causing thrashing on the instance cache. This PR replaces the equality check with a subsumption check.

Use subsumption checks for instance policies

---

conda/conda-build/conda_build_config.yaml
conda/conda-build/meta.yaml

This includes two changes for the conda build scripts:
1. Updates how the restriction on python 3.9.7 is done through run_constrains
2. Updates to 11.8 since SM90 is included in the build command

Update Conda build scripts

---

.github/workflows/ci.yml

Scheduled builds were required when we had a floating legion pointer. Now that we lock to a specific legion commit, schedule builds are no longer required.

Disable scheduled builds

---

legate/driver/args.py
legate/install_info.py.in
legate/util/args.py
legate/util/info.py
legate_core_python.cmake
tests/unit/legate/driver/test_args.py
tests/unit/legate/util/test_args.py

fixes: #632
This PR adds an `--info` command line option to the driver that prints out information about the build configuration:
```
docs310 ❯ legate --info
Legate build configuration:
build_type : Release
use_openmp : True
use_cuda   : True
networks   : None
conduit    : 
```
Questions:
* Would machine-readable (e.g. JSON) output be preferable?
* Currently convert empty list to "None" for "networks" field, is this desired? Could print nothing, or [], or omit the field in this case.
* Prints nothing if there is no conduit, is this desired? Could omit the field, etc. 
cc @manopapad @trxcllnt

add --info command line option

---

legate/driver/command.py
tests/unit/legate/driver/test_command.py

The current nsys flag only checks for `-s` to deduplicate. The user might pass any of the following:
1. --sample <>
1. --sample=<>
1. -s <>
1. -s=<>
The user will get a cryptic error about --sample being passed twice unless they use `-s <>`

More robust nsys --sample flag with --nsys-extra

---

CMakeLists.txt
cmake/legate_helper_functions.cmake
examples/CMakeLists.txt
install.py
legate_core_cpp.cmake

* Example rules were not target-specific, which lead to name clashes when building the examples in-tree
* SKBUILD paths did not set the correct Legate root
* Adds flag to install.py for building examples

Fix example build tests

---

src/core/task/task.cc

Add provenance information to nvtx ranges

---

legate/core/context.py

Thanks once again to @syamajala for finding this.
Turns out `traceback.walk_stack(None)` was always broken, and broke even worse in Python 3.11, see https://github.com/python/cpython/issues/96092.
On my local 3.9 installation, `walk_stack(None)` skips one frame:
```
Trying to find last frame before entering cuNumeric
<frame at 0x7f9bee1952d0, file '/Users/mpapadakis/legate.core/legate/core/context.py', line 368, code wrapper>
__name__ = legate.core.context
<frame at 0x10b02ba00, file 'a.py', line 24, code <module>>
__name__ = __main__
stopped here
The full stack was:
File "/Users/mpapadakis/legion/bindings/python/build/lib/legion_top.py", line 481, in legion_python_main
run_path(args[start], run_name='__main__')
File "/Users/mpapadakis/legion/bindings/python/build/lib/legion_top.py", line …
```

Don't use traceback.walk_stack(None)

---

legate/core/_legion/operation.py
legate/core/runtime.py

This is currently extraneous, as cffi.from_buffer(.) only works with C-contiguous buffers anyway, but good to have this documented.

Guard against attaching to non-contiguous buffers

---

README.md
docs/legate/core/source/conf.py

Need to generate heading anchors and the link must be absolute to work in Sphinx.

Fix documentation issues

---

legate/core/context.py

Currently, even if all nested calls to provenance-tracking functions are recorded, each level will record the same provenance string (*), since they all go all the way up to the first user-level frame. With this change, each time we record provenance we simply use the frame which called into the tracked function. This should be equivalent to the current behavior in cases where nesting is disabled, but should allow us to better track intra-library recursive calls if we want to.
Eventually we will want to be recording all the levels of nesting, in the machine-readable part of the provenance, not just the top or bottom.
(*) Technically if the calls switch between libraries, the stack walking will stop at each library switch, but that doesn't help if we're trying to track recursive calls …

Use parent frame indiscriminately in nested provenance

---

legate/util/fs.py

When using plain Python invocation, startup fails due to `sys.argv[0]` not being the `legate` executable path. 
```
> python -c "import sys; print(sys.argv[0]); import legate.core"
-c
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/raid/wonchanl/miniconda3/envs/registry-env/lib/python3.9/site-packages/legate/core/__init__.py", line 34, in <module>
os.environ.update(driver.env)
File "/raid/wonchanl/miniconda3/envs/registry-env/lib/python3.9/site-packages/legate/driver/driver.py", line 84, in env
return self.launcher.env
File "/raid/wonchanl/miniconda3/envs/registry-env/lib/python3.9/site-packages/legate/driver/launcher.py", line 136, in env
self._env, self._custom_env_vars = self._compute_env()
File "/raid/wonchanl/miniconda3/envs/registry-env/lib/python3.9/si …
```

use legate_dir as basis for non-editable install paths

---

legate/core/_lib/CMakeLists.txt

Fix by @trxcllnt.
Without this addition there would be no `-std=` flag passed to the compiler that's building the cython files, and certain compilers (like Apple clang) fall back to C++98 mode in that case.
This is solving the compilation issue, but apparently the more general solution is for libraries to advertise the minimum C++ standard version that is required by any code in their public headers. For Legion that would be C++11, for Legate it might be C++17, or something lower, depending on what features we use in our public headers (e.g. we use `enable_if_t` in `deserializer.h`, which is C++14 feature, but I think that's not a public header).

Specify C++ standard when building cython sources

---

cmake/legate_helper_functions.cmake
legate/core/_lib/context.pyx
legate/core/context.py
legate/core/launcher.py
legate/core/operation.py
legate/core/runtime.py
legate_core_cpp.cmake
src/core/mapping/base_mapper.cc
src/core/mapping/base_mapper.h
src/core/mapping/core_mapper.cc
src/core/mapping/default_mapper.cc
src/core/mapping/default_mapper.h
src/core/mapping/mapping.h
src/core/mapping/operation.cc
src/core/mapping/operation.h
src/core/runtime/context.cc
src/core/runtime/context.h
src/core/runtime/runtime.cc
src/core/runtime/runtime.h
tests/integration/registry/src/library.cc

Per the internal discussion, this PR implements the following changes to the Legate mapper:
- Libraries can now have only one mapper and should provide their mappers at the registration time.
- When no mapper is given, the default mapper will be used for the library.
- Mapper id parameters have been removed from the APIs where they were expected.
This PR builds on #675 and so it currently inherits all of the changes. I will rebase this PR once #675 is merged.

Mapper refactoring

---

cmake/legate_helper_functions.cmake
src/core/comm/comm.cc
src/core/comm/comm.h
src/core/comm/comm_cpu.cc
src/core/comm/comm_cpu.h
src/core/comm/comm_nccl.cu
src/core/comm/comm_nccl.h
src/core/runtime/projection.cc
src/core/runtime/projection.h
src/core/runtime/runtime.cc
src/core/runtime/shard.cc
src/core/runtime/shard.h
src/core/task/registrar.cc
src/core/task/registrar.h
src/core/task/return.cc
src/core/task/task.h
src/core/task/task.inl
tests/integration/registry/src/library.cc

Some APIs take a `LibraryContext&`, whereas others that are added recently need a `LibraryContext*`. This PR is to make the APIs consistently use `LibraryContext*`.

`LibraryContext*` everywehere

---

src/core/utilities/type_traits.h

`legate::is_float_point` hasn't been returning `true` on `LegateTypeCode::HALF_LT`, even though it should. This PR fixes that issue.

Make `legate::is_floating_point` hold for float16

---

legate_core_cpp.cmake

This include is only necessary when legate is built as a submodule.

Add a missing include to cmake for legate helper functions

---

legate/driver/launcher.py
tests/unit/legate/driver/test_launcher.py

This PR conditions the setting of `REALM_BACKTRACE` depending on whether `PYTHONFAULTHANDLER` is already set. 
@marcinz if we want to set `PYTHONFAULTHANDLER=1` but *only* for the "Eager" job, where can that change be made?

Support PYTHONFAULTHANDLER

---

legate/tester/stages/test_stage.py
legate/tester/test_system.py

This PR makes the tester include any previously set `LEGATE_CONFIG` in the verbose tester output.

special-case tester reporting of LEGATE_CONFIG

---

legate/driver/command.py
legate/install_info.py.in
tests/unit/legate/driver/test_command.py

This PR will make the driver error out with an informative RuntimeError if options like `--gpus` are requested, but the required support is not compiled into the build.

Driver error if legate was compiled w/o required options

---

.github/ops-bot.yaml

Setting up config files to for the rapids ops bot so we can leverage their CI resources in the short-term.
This change only enables the PR copying behavior so that we can submit CI requests from the context of the repo itself. It does **not** enable any workflows against the CI machines yet. Branches are automatically deleted when the associated PR is closed.

Add ops-bot config file

---

scripts/generate-conda-envs.py

Without this, the NumPy packages will side-load libcblas from netlib or MKL. These BLAS alternatives will then be included at runtime in addition to OpenBLAS, and can "shadow" the function implementations that we're trying to use from OpenBLAS.

Force other packages in env to use OpenBLAS as their BLAS backend

---

legate/core/_lib/types.pyx
src/core/data/scalar.h
src/core/type/type_info.cc
src/core/type/type_info.h

Following up on minor (late) comments on https://github.com/nv-legate/legate.core/pull/697

Follow-ups from recent type system changes

---

legate/core/machine.py
src/core/mapping/machine.cc

These were causing single-GPU runs to fail, so they were easy to find. I didn't check other configurations, there might still be some lurking.

Fix off-by-one errors in resource scoping code

---

MANIFEST.in

We will install the interface files ending in the `.pyi` extension to enable proper mypy type checking.

Add interface files to the manifest

---

examples/reduction/src/unique.cc
legate/core/operation.py
tests/integration/tree_reduce/examples/test_tree_reduce.py
tests/integration/tree_reduce/src/tree_reduce_cffi.h

`tree_reduce` wasn't correctly handling cases where the input is produced by a single task.

Fix bugs in corner cases of `tree_reduce`

---

bind.sh

This way we will pick up the correct rank in the case where the user is doing a manual mpirun call inside of a slurm allocation, in which case both SLURM_ and OMPI_ envvars will be present. We now use the OMPI_ ones over the SLURM_ ones, which follows the user's intent.
The reverse (slurm within an mpi call) sounds implausible, so this is IMHO the better polarity.

Prioritize OMPI_ vs SLURM_ envvars when inferring rank

---

cmake/Modules/legate_core_options.cmake
cmake/thirdparty/get_legion.cmake
cmake/versions.json
install.py
legate/driver/command.py
tests/integration/region_manager/CMakeLists.txt
tests/integration/region_manager/editable-install.sh
tests/integration/region_manager/examples/test_region_manager.py
tests/integration/region_manager/install.sh
tests/integration/region_manager/region_manager/__init__.py
tests/integration/region_manager/region_manager/lib.py
tests/integration/region_manager/setup.py
tests/integration/region_manager/src/CMakeLists.txt
tests/integration/region_manager/src/library.cc
tests/integration/region_manager/src/library.h
tests/integration/region_manager/src/region_manager_cffi.h
tests/integration/region_manager/src/tester.cc
tests/integration/region_manager/src/tester.h
tests/unit/legate/driver/test_command.py

We've been suppressing reservation for local fields in each field space by [explicitly passing `-lg:local 0`](https://github.com/nv-legate/legate.core/blob/branch-23.05/legate/driver/command.py#L217), but never been doing the same in the code path for the canonical Python interpreter. So, any code that tries to have more than 252 active stores crashes with the canonical Python interpreter. This PR fixes the issue by just configuring Legion with no local fields. This PR also bumps up the commit hash for Legion, as [Legion's cmake build also had to be updated](https://gitlab.com/StanfordLegion/legion/-/commit/bc69f142bfffba8781c999dc0637ebbc07b2cd10) for this.

Make sure local fields are not enabled for any Python interpreter

---

legate/core/machine.py
src/core/mapping/base_mapper.cc
src/core/runtime/shard.cc

This PR fixes two bugs in the resource scoping code:
1) Node ranges weren't correctly computed to be half-open intervals
2) The base mapper was trying to find initial processors out of empty processor ranges

Fixes for resource scoping

---

legate/core/runtime.py
legate/core/utils.py

Any library that is `dlopen`ed through python's `cffi` will be automatically `dlclose`d when the library object gets collected. This removes certain symbols that may be necessary for destructors that will be called later. This happened to me on MacOS, when running using the canonical python interpreter:
```
Process 56020 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x2a8725418)
frame #0: 0x000000019a8299d9 liblgcore.dylib`std::__1::default_delete<legate::mapping::Mapper>::operator(this=0x0000600003302548, __ptr=0x0000600000229860)[abi:v15006](legate::mapping::Mapper*) const at unique_ptr.h:48:5
45  	  _LIBCPP_INLINE_VISIBILITY void operator()(_Tp* __ptr) const _NOEXCEPT {
46  	    static_assert(sizeof(_Tp) >= 0, "cannot delete an …
```

Don't automatically close dlopen'ed .so's of Legate libs

---

legate/tester/stages/_linux/cpu.py
legate/tester/stages/_linux/gpu.py
legate/tester/stages/_linux/omp.py
legate/tester/stages/_osx/cpu.py
legate/tester/stages/_osx/gpu.py
legate/tester/stages/_osx/omp.py
legate/tester/stages/util.py
legate/util/settings.py
tests/unit/legate/tester/stages/_linux/test_cpu.py
tests/unit/legate/tester/stages/_linux/test_eager.py
tests/unit/legate/tester/stages/_linux/test_gpu.py
tests/unit/legate/tester/stages/_linux/test_omp.py

This PR removes the codepaths that set `CUNUMERIC_TEST` from the `legate.tester`. Corresponding PR in cunumeric removes usage of this flag in favor or `LEGATE_TEST`: https://github.com/nv-legate/cunumeric/pull/922

Unify env test flags

---

legate/core/utils.py

@rohany please confirm this fixes your LLVM JIT loading issue

Load Legate .so's using RTLD_GLOBAL, so they're included in dlopen(NULL)

---

src/core/runtime/context.h
src/core/runtime/context.inl
src/core/runtime/runtime.cc
src/core/runtime/runtime.h
src/core/runtime/runtime.inl

Looks like we don't need to keep track of whether we're in a callback or not.

Stop tracking callbacks

---

conda/conda-build/conda_build_config.yaml
conda/conda-build/meta.yaml
examples/reduction/setup.py
scripts/generate-conda-envs.py

This is no longer used in Legate, and the `libarrow` conda package (required by `pyarrow`) is actually causing issues when building GASNet, because it pulls `ucx` (required for Arrow's `feather` component, which we don't use, but is bundled in the `libarrow` package regardless), which nowadays pulls `rdma-core`, whose `libibverbs.so` conflicts with the system version.

Remove dependency on pyarrow

---

conda/conda-build/meta.yaml

Libraries are linking to cudart.so.11 so we need to lock the run time dependency to the major version being used during compilation

Locking cuda-cudart to a major version

---

legate/tester/args.py
legate/tester/config.py
legate/tester/stages/test_stage.py
legate/tester/stages/util.py
legate/tester/test_plan.py
legate/tester/test_system.py
legate/util/ui.py
tests/unit/legate/tester/stages/test_util.py
tests/unit/legate/tester/test_args.py
tests/unit/legate/tester/test_config.py
tests/unit/legate/tester/test_test_system.py
tests/unit/legate/util/test_ui.py

This PR adds an new `--timeout` option to the tester code that can be used to diagnose infinite hangs. When `--timeout` is specified, and a test exceeds this amount, it will be terminated, and report as `[TIME]` in the running test log. All timed-out tests are also reported in one place at the end:
Additionally, this PR adds support to display per-test time information:
This feature is probably best used as a diagnostic tool for specific situations, rather than enabled by default. Given the extreme ranges of hardware and tests that may be encountered, there is not a reasonable "global default". Instead, when a hanging test is encountered, the `--timeout` may be set in order to determine what test is hanging. 
Lastly, if GPU tests timeout it appears that some subsequent tests run before …

Add support for test timeouts

---

cmake/versions.json
install.py

This PR adds support for specifying `--gasnet-system` to `install.py`. This is useful for some specialized systems such as Perlmutter. I have not had a chance to test this there yet, as Perlmutter is down for maintenance today, but the generated `cmake` invocations look correct locally. 
This PR also updates the legion repo commit pin to the latest HEAD of `control_replication`

Add support for --gasnet-system

---

legate/tester/stages/test_stage.py

Currently a worker will pick a new shard out of the global queue (in FIFO order) as it starts each test. In cases where one test is taking significantly longer than others, it might happen that enough other workers pick up the same shard as the slow worker, leading to oversubscription and OOM-adjacent issues. Consider the following testing run on a DGX-1V box with 8x 16GB GPUs:
```
mpapadakis@prm-dgx-02:/home/scratch.mpapadakis_sw/py-legate/cunumeric$ for F in temp/*.py; do echo $F; cat $F; echo; done
temp/a.py
from time import sleep
sleep(10)
temp/b.py
from time import sleep
sleep(3)
temp/c.py
from time import sleep
sleep(3)
```
<details>
<summary>Original output</summary>
```
mpapadakis@prm-dgx-04:/home/scratch.mpapadakis_sw/py-legate/cunumeric$ …
```

Have each test worker stick to its original shard

---

legate/tester/stages/util.py
legate/tester/test_system.py
tests/unit/legate/tester/stages/test_util.py

This PR adds start and end timestams to the test output, in case it is needed for detailed observation of the test plan exectution.

Add start/end timestamps to test results

---

src/core/utilities/span.h

The expression `&data[size_]` is forming a reference to the last+1 element of the range. That memory address may not be dereferencable.
Rather than forming a reference and taking the address, we can obtain the same result with some simple pointer arithmetic.

avoid undefined behavior in `Span::end`

---

CMakeLists.txt
cmake/legate_helper_functions.cmake
legate_core_cpp.cmake
legate_core_python.cmake

Works around https://github.com/nv-legate/cunumeric/issues/835 until https://github.com/rapidsai/rapids-cmake/issues/426 is addressed.
Also take this opportunity to bump rapids-cmake version.

Set lib_dir explicitly to lib/, even on RHEL

---

scripts/generate-conda-envs.py

@manopapad for some reason the original code does not work on perlmutter `module python` (3.9) during bootstrapping instructions. I think this is fine though/

usage of protocol does not work with 3.9

---

docs/legate/core/source/api/runtime.rst
legate/core/launcher.py
legate/core/runtime.py
tests/unit/legate/core/test_type_cache.py

This PR adds a small type cache for array-typed scalar arguments so their types are deduplicated. Creating a fresh array type whenever an array-typed scalar argument is passed to a task turns out to be problematic for any attempt to cache task metadata.

Add a small type cache for array-typed scalar arguments

---

src/core/data/store.cc
src/core/data/store.h
src/core/data/store.inl

This PR makes two changes to error checking for `legate::Store`
1) Type validation for reduction accessors (was missing in #745)
2) Exceptions instead of `LEGATE_ABORT`

More error checking for stores

---

legate/core/_legion/future.py
legate/core/runtime.py

Legion recently changed future map reductions to be ordered by default so all the shards would see the same results, but Legate hasn't been using them, which this PR fixes.

Use ordered future map reductions by default

---

conda/conda-build/meta.yaml

Backport #798 from `branch-23.07`.

pin cuda-version

---

legate/core/__init__.py

We want to seed `np.random` and `random` to avoid control-replication violations when running multi-rank.
We also want to warn users who tries to call `seed` inside of their code (python side)

Pre-seeding random nuber generators

---

legate/driver/args.py
legate/driver/command.py
legate/driver/config.py
legate/jupyter/config.py
tests/unit/legate/driver/test_args.py
tests/unit/legate/driver/test_command.py
tests/unit/legate/driver/test_config.py
tests/unit/legate/jupyter/test_config.py

This PR adds two new command line options `--wrapper` and `--wrapper-inner` to allow users to insert their own custom wrapper executables int the legate invocation chain. 
Both wrappers come after `bind.sh` so that `%%LEGATE_GLOBAL_RANK%%` can be expanded in the invocation.

Add support for custom wrappers

---

scripts/generate-conda-envs.py

The sections flag can be used to exclusively select specified sections in the generated YAML file. Example usage...
```
> generate_conda_envs.py --os linux  --ctk 11.8 --python 3.10 --sections tests
```

Added a sections flag to generate_conda_envs.py

---

src/core/comm/comm_nccl.cu
src/core/runtime/runtime.cc
src/core/runtime/runtime.h

The NCCL initialization task has been performing all-to-all and all-gather to warm up NCCL. This makes it impossible for users to disentangle how much of the task execution time is attributed to the communicator creation vs. the warm-up. This PR makes two changes to the task:
1) the warm-up NCCL calls are performed only when `LEGATE_WARMUP_NCCL` is set to 1;
2) the NCCL initialization task starts to report timings for communicator creation and warm-up at the `DEBUG` logging level (`--logging legate=1` is needed to see them).

Make NCCL warm-up optional

---

legate/driver/args.py
legate/driver/config.py
legate/driver/driver.py
legate/jupyter/config.py
tests/unit/legate/driver/test_args.py
tests/unit/legate/driver/test_config.py
tests/unit/legate/jupyter/test_config.py

This PR addds a basic `--timing` option to the driver, that, when enabled, prints "Legate start" and "Legate end" timestamps to stdout. Currently the timestamps are inclusive of Python's `subprocess.run` overhead.
Run on a single file, it looks like:
```
dev310 ❯ LEGATE_TEST=1 legate --timing /home/bryan/work/cunumeric/tests/integration/test_binary_op_complex.py  -v  
Legate start: 2023-08-10 14:26:27.029508
====================================================================================================== test session starts =======================================================================================================
platform linux -- Python 3.10.11, pytest-7.4.0, pluggy-1.0.0 -- /home/bryan/anaconda3/envs/dev310/bin/python3
cachedir: .pytest_cache
rootdir: …
```

Add simple --timing flag to driver

---

scripts/generate-conda-envs.py

`Pynvml` is a test dependency for `cunumeric` so it needs to be present in the tests section even if it is already present in the cuda section. Because generating an env def file with the `--sections tests` flag will otherwise produce an incomplete environment.

Add pynvml as a test dependency in generate_conda_envs.py.

---

legate/tester/__init__.py
legate/tester/args.py
legate/tester/config.py
legate/tester/stages/_linux/gpu.py
tests/unit/legate/tester/test___init__.py
tests/unit/legate/tester/test_config.py

This PR adds `--bloat-factor` to the tester  command line options, in order to tweak GPU memory allocations if needed.

Expose bloat factor config

---

BUILD.md

updating cuda toolkit version in documentation on manual install since we now require it to be >=11.8

updating cuda toolkit version in documentation

---

conda/conda-build/build.sh
conda/conda-build/conda_build_config.yaml

Reverts changes to the conda build files accidentally introduced in https://github.com/nv-legate/legate.core/pull/828.

Revert accidental changes to `conda build` files

---

legate/driver/args.py
legate/util/shared_args.py
tests/unit/legate/driver/test_args.py

fixes: #829 
This PR add support to modulate the default `nodes` and `ranks_per_node` values in the presence of common relevant environment variables. This is most useful when legate is "externally launched" but the `--help` string is updated with the corresponding information when this occurs:
```
--nodes NODES         Number of nodes to use [default auto-detected from OMPI] (default: 4)
--ranks-per-node RANKS_PER_NODE
Number of ranks (processes running copies of the program) to launch per node. [default auto-detected from OMPI] (default: 2)
```

auto-detect multi-node based on env vars

---

legate/core/_legion/future.py
legate/core/_legion/region.py
legate/core/cycle_detector.py
legate/core/launcher.py
legate/core/store.py

This PR resolves this class of new `flake8` errors:
> legate/core/_legion/future.py:52:16: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
All `legate.core` and `cunumeric` tests were checked locally to pass. Still it's unclear if some of the instances really do intend strict type equality. If so those can be changed back with a `# noqa` added.

Satisfy new flake8 type check rules

---

legate/util/system.py
tests/unit/legate/util/test_system.py

Handle both ranges and individual values

Expand ranges when reading thread_siblings_list

---

BUILD.md
scripts/generate-conda-envs.py

These libraries used to be included automatically with one of the other CUDA packages, but not anymore, so we have to include them manually.

Add missing 12.0 CUDA libraries to env generation script

---

continuous_integration/home/coder/.local/bin/run-test-or-analysis

Fix the mypy version in CI since 1.6 has some new (unaddressed) warnings.

Set Mypy version downloaded in CI

---

conda/conda-build/meta.yaml

I saw an issue discussed offline by @csadorf and @m3vaz. The core problem was that legate.core had a high constraint on `numpy>=1.26` despite the build scripts requesting `numpy >=1.22`. I filed #854 to solve this by pinning the build dependency on numpy but then realized that it seems to be only a runtime dependency. I couldn't find any reliance on numpy in the build scripts, nor use of the Cython API like `cimport numpy` or C API, so I think this is safe to remove. Removing this from the `host:` section of the conda recipe will resolve this problem.
The screenshot below shows two numpy dependencies being added to this package. The constraint `numpy >=1.22` is coming from the `run:` pinning, while the `numpy >=1.26.0,<2.0a0` is coming from a run_exports on the `numpy >=1.22` being …

Remove numpy from conda build dependencies.

---

legate/issue.py
setup.py

This PR adds a new entry point `legate-issue` that prints out information that is useful for GitHub issues. We can create a GH issue template to suggest (or require) including the output of this command up-front. 
Sample output on my system:
```
dev310 ❯ legate-issue 
Python      :  3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
Platform    :  Linux-5.14.0-1042-oem-x86_64-with-glibc2.31
Legion      :  v23.11.00.dev-16-g2499f878
Legate      :  23.11.00.dev+17.gb7b50313
Cunumeric   :  (ImportError: cannot import name 'LogicalArray' from 'legate.core')
Numpy       :  1.24.4
Scipy       :  1.10.1
Numba       :  (not installed)
CTK package : cuda-version-11.8-h70ddcb2_2 (conda-forge)
GPU Driver  : 515.65.01
GPU Devices :
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX …
```

Add legate-issue command for collecting issue info

---

legate/core/_lib/__init__.py

This clears the `pip install` warning about "Package would be ignored" described in #862
All `cunumeric` tests pass when built against an wheel install with this change. Since we do intend there to be `legate.core._lib` package, this seems like the correct action, or at the very least, a harmless resolution.

make _lib a proper module

---

legate/driver/launcher.py

It doesn't seem like this is necessary. Removing it because on non-editable installations it ends up adding `<venv-root>/lib/pythonX.Y/site-packages/legate` to the `PYTHONPATH`, which causes sub-modules under legate to potentially clash with top-level modules of the same name.

Remove extraneous PYTHONPATH entry

---

tests/unit/legate/driver/test_command.py

This PR makes the "bgwork" tests explicitly control the presence of `"ucx"` in `install_info.networks` in all cases. Previously, tests always simply assumed "ucx" was absent *by default* which fails as soon as testing happens on a system that does actually have UCX enabled. 
cc @mag1cp1n

control ucx presence in install_info more carefully

---

legate/core/store.py

adding a workaround  for NumPy's expected behavior when adding an integer to np.uint64, resulting in float64
see https://github.com/numpy/numpy/issues/5745

adding a workaround  for NumPy's conversion from unit64 to float

---

legate/driver/driver.py
legate/driver/main.py
tests/unit/legate/driver/test_driver.py

This PR prevents informational messages, e.g. profiling output locations, from being printed on every node in a multi-node scenario.

Print driver output only on head nodes

---

scripts/generate-conda-envs.py

Package versions on the nvidia channel don't always correspond to CTK version (e.g. cusparse 12.2 can be part of CTK 12.3). The only robust way to ensure that all selected nvidia conda channel packages are coming from a compatible CTK collection is to restrict based on label.

Use labels from the nvidia channel to restrict CTK versions

---

.github/workflows/ci-gh-build-release.yml
.github/workflows/ci-gh-docs.yml
.github/workflows/ci-gh.yml
.github/workflows/gh-build-and-test.yml
BUILD.md
cmake/thirdparty/get_legion.cmake
conda/conda-build/meta.yaml
continuous_integration/scripts/build-legate
continuous_integration/scripts/build-legate-conda
continuous_integration/scripts/build-legate-cpp
continuous_integration/scripts/build-legate-wheel
continuous_integration/scripts/conda-utils
continuous_integration/scripts/run-test-or-analysis
continuous_integration/scripts/setup-utils
scripts/conda-build.sh
scripts/generate-conda-envs.py
tests/unit/legate/tester/stages/test_test_stage.py

Adding this package should resolve the build issues that have cropped up recently.
Issues that came up in the process:
- Fixed the runner that does not exist anymore
- Update cuda version to a format introduced in another PR
- Update the documentation
- Change to using labels for the nvidia channel
- Fix a test issue that was crashing the tests on OS X
- Do not use GPU runners for CPU tests
- Provide an option for not building the profiler and turn it off in the CI builds (provides a good speedup)
- Switch to using cuda 12.2.2
- Require that cuda is installed (__cuda requirement) in the meta.yaml, but do not request any specific version
- Add openmpi to requirements if we build with UCX

Add cuda-cudart-static to generated conda environments

---

cmake/thirdparty/get_legion.cmake

Previously passing `--profiler` didn't actually do anything.

Fix build of rust profiler

---

legate/driver/args.py
tests/unit/legate/driver/test_args.py

This PR makes the detection of multi-node configurations (especially for SLURM) more robust.

improve multi-node detection

---

legate/driver/args.py
tests/unit/legate/driver/test_args.py

We're seeing it reported e.g. as "1(x2)"

SLURM_TASKS_PER_NODE is not always an integer

---

legate/driver/args.py
tests/unit/legate/driver/test_args.py

This PR allows for correct handling of cases like SLURM_TASKS_PER_NODE="3(x2)"`

handle SLURM_TASKS_PER_NODE more thoroughly

---

legate/driver/driver.py
legate/driver/launcher.py
legate/util/system.py
tests/unit/legate/driver/test_driver.py
tests/unit/legate/driver/test_launcher.py
tests/unit/legate/util/test_system.py

There is no reason anymore to mess with `LD_LIBRARY_PATH` and friends. Our binaries and libraries nowadays have `RPATH` set appropriately, and the python interpreter should be able to locate cython extensions even under editable installation by looking through `PYTHONPATH`.  Our canonical python support works by accident due to https://github.com/StanfordLegion/legion/issues/1443, which is not ideal, but the plan is to get rid of this path soon, so I'm not worried about that.

Stop setting LD_LIBRARY_PATH in the launcher

---

cmake/thirdparty/get_legion.cmake
cmake/versions.json
src/core/mapping/base_mapper.cc
src/core/mapping/base_mapper.h

The flag `--root` here is a workaround for buggy behavior in `pip install` where pip would ignore the `--prefix` setting when `--global-option` was supplied. As it turns out, `--global-option` is deprecated anyway so we removed in Legion. As a result, this is no longer required; the prefix is already set in the upstream project and the need for `--root` goes away with the removal of `--global-option`.
See this Legion MR for details:
https://gitlab.com/StanfordLegion/legion/-/merge_requests/1072
I'm not sure which branch to send this patch to so if I'm set the wrong one, let me know and I'll update it.

Remove unnecessary flags in Legion CMake build

---

cmake/thirdparty/get_legion.cmake
cmake/versions.json
src/core/mapping/base_mapper.cc
src/core/mapping/base_mapper.h

This reverts commit 5d74fdc115f6a4b06baa3f145d2a837c24126974.
CI had not actually fully succeeded on #932, rather the bot was waiting for us to tell it "\ok to test" again, and there is no indication that this was required on the test results.
So reverting this, and will reopen it to try and fix the errors.

Revert "Remove unnecessary flags in Legion CMake build (#932)"

---

cmake/thirdparty/get_legion.cmake
cmake/versions.json
src/core/mapping/base_mapper.cc
src/core/mapping/base_mapper.h

Redoing #932 to fix CI issues without affecting the main branch

Remove unnecessary flags in Legion CMake build (#932)

---

continuous_integration/scripts/conda-utils

The `--force` argument was deemed necessary in the past (for reasons currently unknown), but it is incorrect and causes mamba crashes.

Remove incorrect argument to mamba

---

BUILD.md
README.md

This PR adds a link to the conda docs and also specifies a min conda version to use to ensure that the latest legate versions are properly picked up.

Specify min conda version
